//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileExplorer.Wpf.Resources {
  /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileExplorerSettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileExplorerSettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(FileExplorerSettingsResources.resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hell.LogDown.Resources.FileExplorerSettingsResources", typeof(FileExplorerSettingsResources).Assembly);
                    FileExplorerSettingsResources.resourceMan = temp;
                }
                return FileExplorerSettingsResources.resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return FileExplorerSettingsResources.resourceCulture;
            }
            set {
                FileExplorerSettingsResources.resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autoOpenFileList.
        /// </summary>
        internal static string AutoOpenFilesSectionName {
            get {
                return FileExplorerSettingsResources.ResourceManager.GetString("AutoOpenFilesSectionName", FileExplorerSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customFilters.
        /// </summary>
        internal static string CustomFiltersSectionName {
            get {
                return FileExplorerSettingsResources.ResourceManager.GetString("CustomFiltersSectionName", FileExplorerSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to defaultFilters.
        /// </summary>
        internal static string DefaultFiltersSectionName {
            get {
                return FileExplorerSettingsResources.ResourceManager.GetString("DefaultFiltersSectionName", FileExplorerSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filters.
        /// </summary>
        internal static string FilterSectionName {
            get {
                return FileExplorerSettingsResources.ResourceManager.GetString("FilterSectionName", FileExplorerSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recentFiles.
        /// </summary>
        internal static string RecentFileSectionName {
            get {
                return FileExplorerSettingsResources.ResourceManager.GetString("RecentFileSectionName", FileExplorerSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileExplorerSettings.
        /// </summary>
        internal static string SectionGroupName {
            get {
                return FileExplorerSettingsResources.ResourceManager.GetString("SectionGroupName", FileExplorerSettingsResources.resourceCulture);
            }
        }
    }
}
