//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileExplorer.Wpf.Resources {
  /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalSettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalSettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(GlobalSettingsResources.resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hell.LogDown.Resources.GlobalSettingsResources", typeof(GlobalSettingsResources).Assembly);
                    GlobalSettingsResources.resourceMan = temp;
                }
                return GlobalSettingsResources.resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return GlobalSettingsResources.resourceCulture;
            }
            set {
                GlobalSettingsResources.resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documentIsShowingHiddenTags.
        /// </summary>
        internal static string DocumentIsShowingHiddenTags {
            get {
                return GlobalSettingsResources.ResourceManager.GetString("DocumentIsShowingHiddenTags", GlobalSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to externalFileEditorCommandLineArgs.
        /// </summary>
        internal static string ExternalFileEditorCommandLineArgs {
            get {
                return GlobalSettingsResources.ResourceManager.GetString("ExternalFileEditorCommandLineArgs", GlobalSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to externalFileEditor.
        /// </summary>
        internal static string ExternalFileEditorPath {
            get {
                return GlobalSettingsResources.ResourceManager.GetString("ExternalFileEditorPath", GlobalSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isLiveSearchEnabled.
        /// </summary>
        internal static string IsLiveSearchEnabled {
            get {
                return GlobalSettingsResources.ResourceManager.GetString("IsLiveSearchEnabled", GlobalSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isMainToolBarAutoHideEnabled.
        /// </summary>
        internal static string IsMainToolBarAutoHideEnabled {
            get {
                return GlobalSettingsResources.ResourceManager.GetString("IsMainToolBarAutoHideEnabled", GlobalSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isRestoringMainWindowPositionOnStart.
        /// </summary>
        internal static string IsRestoringMainWindowPositionOnStart {
            get {
                return GlobalSettingsResources.ResourceManager.GetString("IsRestoringMainWindowPositionOnStart", GlobalSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mainWindowHeight.
        /// </summary>
        internal static string MainWindowHeight {
            get {
                return GlobalSettingsResources.ResourceManager.GetString("MainWindowHeight", GlobalSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mainWindowState.
        /// </summary>
        internal static string MainWindowState {
            get {
                return GlobalSettingsResources.ResourceManager.GetString("MainWindowState", GlobalSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mainWindowWidth.
        /// </summary>
        internal static string MainWindowWidth {
            get {
                return GlobalSettingsResources.ResourceManager.GetString("MainWindowWidth", GlobalSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxConcurrentDocuments.
        /// </summary>
        internal static string MaxConcurrentDocuments {
            get {
                return GlobalSettingsResources.ResourceManager.GetString("MaxConcurrentDocuments", GlobalSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to globalSettings.
        /// </summary>
        internal static string SectionGroupName {
            get {
                return GlobalSettingsResources.ResourceManager.GetString("SectionGroupName", GlobalSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global.
        /// </summary>
        internal static string SectionName {
            get {
                return GlobalSettingsResources.ResourceManager.GetString("SectionName", GlobalSettingsResources.resourceCulture);
            }
        }
    }
}
