//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileExplorer.Wpf.Resources {
  /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SynchronizationSettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SynchronizationSettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(SynchronizationSettingsResources.resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hell.LogDown.Resources.SynchronizationSettingsResources", typeof(SynchronizationSettingsResources).Assembly);
                    SynchronizationSettingsResources.resourceMan = temp;
                }
                return SynchronizationSettingsResources.resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return SynchronizationSettingsResources.resourceCulture;
            }
            set {
                SynchronizationSettingsResources.resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documentIdColorPresets.
        /// </summary>
        internal static string DocumentIdColorPresets {
            get {
                return SynchronizationSettingsResources.ResourceManager.GetString("DocumentIdColorPresets", SynchronizationSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isSyncAllOpenDocumentsEnabled.
        /// </summary>
        internal static string IsSyncAllOpenDocumentsEnabled {
            get {
                return SynchronizationSettingsResources.ResourceManager.GetString("IsSyncAllOpenDocumentsEnabled", SynchronizationSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liveMergeRangeInLines.
        /// </summary>
        internal static string LiveMergeRangeInLines {
            get {
                return SynchronizationSettingsResources.ResourceManager.GetString("LiveMergeRangeInLines", SynchronizationSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mergeRangeInLines.
        /// </summary>
        internal static string MergeRangeInLines {
            get {
                return SynchronizationSettingsResources.ResourceManager.GetString("MergeRangeInLines", SynchronizationSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mergeRangeInTime.
        /// </summary>
        internal static string MergeRangeInTime {
            get {
                return SynchronizationSettingsResources.ResourceManager.GetString("MergeRangeInTime", SynchronizationSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileSynchronizationSettings.
        /// </summary>
        internal static string SectionGroupName {
            get {
                return SynchronizationSettingsResources.ResourceManager.GetString("SectionGroupName", SynchronizationSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileSynchronization.
        /// </summary>
        internal static string SectionName {
            get {
                return SynchronizationSettingsResources.ResourceManager.GetString("SectionName", SynchronizationSettingsResources.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mode.
        /// </summary>
        internal static string SynchronizationMode {
            get {
                return SynchronizationSettingsResources.ResourceManager.GetString("SynchronizationMode", SynchronizationSettingsResources.resourceCulture);
            }
        }
    }
}
